import Head from "next/head";
import { PropTypes } from "prop-types";
import React from "react";

const Index = ({ title }) => {
  return (
    <Head>
      <title>{title}</title>
      <meta content="Generated by create next app" name="description" />
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <link href="/favicon.ico" rel="icon" />
    </Head>
  );
};

Index.defaultProps = {};

Index.propTypes = {
  title: PropTypes.string.isRequired,
};

export default Index;
