import LandingPage from "components/landingPage/LandingPage";
import { useSession } from "next-auth/react";
import Head from "next/head";

import styles from "./index.module.scss";

export default function Home() {
  const { data: session, status } = useSession();

  console.log("session, status here:", session, status);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta content="Generated by create next app" name="description" />
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <main className={styles.main}>
        <LandingPage />
      </main>
    </>
  );
}
